config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#show', id: 'home'
  get 'pages/:id', to: 'pages#show', as: :page, format: false
  
  resource :protected_pages, only: [:show], format: false

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :fido_usf_registerable, :fido_usf_authenticatable, :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prepend the verification of the CSRF token before the action chain.
  protect_from_forgery with: :exception, prepend: true
  # All pages are only allowed for authenticated users.
  # Visitor pages will be excepted from this rule explicitly.
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage

  # Do not authenticate users. Service pages to whole internet.
  skip_before_action :authenticate_user!
end

app/controllers/protected_pages_controller.rb
class ProtectedPagesController < ApplicationController

  # Only show a single page
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options={})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=404"
    gravatar_class = options[:class].blank? ? "gravatar" : options[:class]
    unless options[:size].blank?
      gravatar_url << "&s=%d"%options[:size]
    end
    image_opts={alt: user.email , class: gravatar_class}
    unless options[:tooltip].blank?
      image_opts.merge! rel: 'tooltip', title: options[:tooltip]
    end
    content_tag('span', image_tag(gravatar_url, image_opts), "aria-hidden" => "true")
  end

  def full_title(page_title)
    base_title = I18n.t('site.short_title')
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def settings_row(head, subline, options={}, &block) 
    options.reverse_merge!(width: 9)

    heading = options.key?(:decorate) ? content_tag(:h3, head, class: "#{options[:decorate]}") : content_tag(:h3, head)
    heading_subline = options.key?(:decorate) ? content_tag(:p, subline, class: "text-muted #{options[:decorate]}") : content_tag(:p, subline, class: "text-muted")
    content = options.key?(:id) ? content_tag(:div, class: "col-lg-#{options[:width]}", id: options[:id]) { yield } : content_tag(:div, class: "col-lg-#{options[:width]}") { yield }

    content_tag(:div, class: 'row') do
      content_tag(:div, class: 'col-lg-3') do
        heading + heading_subline
      end + 
      content
    end
  end
end

app/views/layouts/_logo.html.erb
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 400 140" enable-background="new 0 0 400 140" xml:space="preserve" height="32" class="logo">
<title>rails-logo</title>
<g>
	<path class="a" d="M346.6,121.5v18.1c0,0,23.4,0,32.7,0c6.7,0,18.2-4.9,18.6-18.6c0-0.6,0-6.5,0-7c0-11.7-9.6-18.6-18.6-18.6
		c-4.2,0-16.3,0-16.3,0V87l32.3,0V68.8c0,0-22.2,0-31,0c-8,0-18.7,6.6-18.7,18.9c0,1.2,0,5.2,0,6.3c0,12.3,10.6,18.6,18.7,18.6
		c22.5,0.1-5.4,0,15.4,0c0,8.8,0,8.8,0,8.8"/>
	<path class="a" d="M171.4,117.1c0,0,17.5-1.5,17.5-24.1s-21.2-24.7-21.2-24.7h-38.2v71.3h19.2v-17.2l16.6,17.2h28.4
		L171.4,117.1z M164,102.5h-15.3V86.2h15.4c0,0,4.3,1.6,4.3,8.1S164,102.5,164,102.5z"/>
	<path class="a" d="M236.3,68.8c-4.9,0-5.6,0-19.5,0c-13.9,0-18.6,12.6-18.6,18.6c0,13,0,52.2,0,52.2h19.5v-12.5H236v12.5h18.9
		c0,0,0-38.5,0-52.2C254.9,72.2,241.1,68.8,236.3,68.8z M236,106.9h-18.4V89.6c0,0,0-3.9,6.1-3.9c5.6,0,1,0,6.7,0
		c5.4,0,5.5,3.9,5.5,3.9V106.9z"/>
	<rect x="263.8" y="68.8" class="a" width="20.3" height="70.8"/>
	<polygon class="a" points="312.6,121.3 312.6,68.8 292.4,68.8 292.4,121.3 292.4,139.6 312.6,139.6 339.9,139.6 339.9,121.3 	
		"/>
	<path class="a" d="M9,139.6h79c0,0-15.1-68.9,34.9-96.8c10.9-5.3,45.6-25.1,102.4,16.9c1.8-1.5,3.5-2.7,3.5-2.7
		S176.8,5.1,118.9,10.9C89.8,13.5,54,40,33,75S9,139.6,9,139.6z"/>
	<path class="a" d="M9,139.6h79c0,0-15.1-68.9,34.9-96.8c10.9-5.3,45.6-25.1,102.4,16.9c1.8-1.5,3.5-2.7,3.5-2.7
		S176.8,5.1,118.9,10.9C89.8,13.5,54,40,33,75S9,139.6,9,139.6z"/>
	<path class="a" d="M9,139.6h79c0,0-15.1-68.9,34.9-96.8c10.9-5.3,45.6-25.1,102.4,16.9c1.8-1.5,3.5-2.7,3.5-2.7
		S176.8,5.1,118.9,10.9C89.7,13.5,53.9,40,32.9,75S9,139.6,9,139.6z"/>
	<path class="a" d="M173.6,16.5l0.4-6.7c-0.9-0.5-3.4-1.7-9.7-3.5l-0.4,6.6C167.2,14,170.4,15.2,173.6,16.5z"/>
	<path class="a" d="M164.1,37.7l-0.4,6.3c3.3,0.1,6.6,0.5,9.9,1.2l0.4-6.2C170.6,38.3,167.3,37.9,164.1,37.7z"/>
	<path class="a" d="M127.1,6.5c0.3,0,0.7,0,1,0l-2-6.1c-3.1,0-6.3,0.2-9.6,0.6l1.9,5.9C121.3,6.6,124.2,6.5,127.1,6.5z"/>
	<path class="a" d="M131.9,43.3l2.3,6.9c2.9-1.4,5.8-2.6,8.7-3.5l-2.2-6.6C137.3,41.1,134.4,42.2,131.9,43.3z"/>
	<path class="a" d="M86.5,17L82,10.1c-2.5,1.3-5.1,2.7-7.8,4.3l4.6,7C81.4,19.8,83.9,18.3,86.5,17z"/>
	<path class="a" d="M107,62l4.8,7.2c1.7-2.5,3.7-4.8,5.9-7.1l-4.5-6.8C110.9,57.4,108.8,59.7,107,62z"/>
	<path class="a" d="M92.5,94.2l8.1,6.4c0.4-3.9,1.1-7.8,2.1-11.7l-7.2-5.7C94.2,86.9,93.3,90.6,92.5,94.2z"/>
	<path class="a" d="M48.7,46.7l-7.1-6.2c-2.6,2.5-5.1,5-7.4,7.5l7.7,6.6C44,51.9,46.3,49.2,48.7,46.7z"/>
	<path class="a" d="M18.5,91.4L7,87.2c-1.9,4.3-4,9.3-5,12l11.5,4.2C14.8,100,16.9,95.1,18.5,91.4z"/>
	<path class="a" d="M91,119.6c0.2,5.3,0.7,9.6,1.2,12.6l12,4.3c-0.9-3.9-1.8-8.3-2.4-13L91,119.6z"/>
</g>
</svg>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed- top">
  <%= link_to render('layouts/logo'), root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link' %></li>
    </ul>
    <ul class="navbar-nav">
    <% if not signed_in? %>
      <li class="nav-item nav-item-btn"><%= link_to t('devise.sessions.sign_in'), new_user_session_path(), class: 'btn btn-outline-primary' %></li>
      <li class="nav-item nav-item-btn"><%= link_to t('devise.registrations.register'), new_user_registration_path(), class: 'btn btn-outline-secondary' %></li>
    <% else %>
      <li class="nav-item mr-3"><%= link_to gravatar_for(current_user, size: 38, class: "rounded-circle"), edit_user_registration_path() %></li>
      <li class="nav-item nav-item-btn"><%= link_to t('devise.sessions.sign_out'), destroy_user_session_path(), method: 'delete', class: 'btn btn-outline-primary' %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for?(:title) ? full_title(yield(:title)) : full_title('') %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Example Application Standard description" %>">
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'cookies_eu/consent_banner', link: page_path(id: 'cookies') %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/cookies.html.erb
<% provide(:title, t('site.page.cookies')) %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h3 class="display-3" id="cookies"><%= t('site.page.cookies') %></h3>
      <p class="lead">Cookies are small text files which are downloaded to your computer, tablet or mobile phone when you visit a website or application.</p>
      <p>The website or application may retrieve these cookies from your web browser (eg Internet Explorer, Mozilla Firefox or Google Chrome) each time you visit, so they can recognise you, remember your preferences and provide you with a more secure online experience.</p>
      <p>Generally, cookies are very useful and are a common method used by almost every website you visit because they help to make your online experience as smooth as possible. For security reasons, many websites will not function at all without the use of cookies (or other similar technologies, such as "web beacons" or "tags").</p>
      <p>Cookies generally do not hold any information to identify an individual person, but are instead used to identify a browser on an individual machine.</p>
      <p>If you prefer, you can restrict, block or delete cookies by changing your browser settings but that may mean that the website won't work properly</p>
      <p>For more information about cookies and their impact on you and your browsing visit <%= link_to 'http://www.aboutcookies.org', 'http://www.aboutcookies.org', target: '_blank' %>.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h3 class="card-header">Types of Cookies</h3>
        <div class="card-body">
          <h4 class="card-title">Necessary cookies</h4>
          <p class="card-text">These cookies are essential in helping you to make use of the features and services we offer on the <%= t('site.long_title') %> website. Without these cookies, the services you want to use cannot be provided. These cookies do not gather information about you that could be used to identify you, and they do not monitor or remember where you have been on the internet.</p>
          <h4 class="card-title">Functional cookies</h4>
          <p class="card-text">These cookies allow us to provide you with a better online experience when you use our website. They do not gather or store any information which would allow us to identify you personally.</p>
          <h4 class="card-title">Performance cookies</h4>
          <p class="card-text">Performance cookies help us to understand how our customers use our site, so we can keep our products and services relevant, easy to use and up to date. For example, we can see which products and services are most popular, identify when and where errors occur, and test different versions of a page in order to provide an improved online experience.</p>
          <p class="card-text">Sometimes, the services we use to collect this information may be operated by other companies on our behalf. They may use similar technologies to cookies, known as "web beacons" or "tags". These are anonymous and, as they are only used for statistical purposes, they do not contain or collect any information that identifies you.</p>
          <h4 class="card-title">Targeting cookies</h4>
          <p class="card-text">We have relationships with carefully selected and monitored suppliers (third parties) who may also set cookies during your visit. The purpose of these cookies is "behavioural advertising" (also known as "behavioural targeting" or "remarketing"), which is a means of showing you relevant products and services based on what you appear to be interested in. Although these cookies can track your visits around the web they don't know who you are. Without these cookies, online advertisements you encounter will be less relevant to you and your interests.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card mt-3">
        <h3 class="card-header">Managing Cookies</h3>
        <div class="card-body">
          <p class="card-text">Most internet browsers allow you to erase cookies from your computer hard drive, block all cookies (or just third-party cookies) or warn you before a cookie is stored on your device.</p>
          <p class="card-text">Please note, if you choose to block all cookies, our site will not function as intended and you will not be able to use or access many of the services we provide. If you have blocked all cookies and wish to make full use of the features and services we offer, you will need to enable your cookies. You can do this in your browser (see below).</p>
          <p class="card-text">Rather than blocking all cookies, you can choose to only block third-party cookies which will still allow our website to function as intended.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row mb-5">
    <div class="col-lg-6">
      <div class="card mt-3">
        <h3 class="card-header">How to manage cookies on your PC</h3>
        <div class="card-body">
          <p class="card-text">To enable cookies on our website, follow the steps below.</p>
          <h4 class="card-title">Google Chrome</h4>
          <ol>
            <li>Click "Tools" at the top of your browser and select "Settings".</li>
            <li>Click "Show advanced settings", scroll down to the section "Privacy" and click "Content Settings."</li>
            <li>Select "Allow local data to be set". To only acept first-party cookies, check the box next to "Block all third-party cookies without exception"</li>
          </ol>
          <h4 class="card-title">Microsoft Internet Explorer 6.0, 7.0, 8.0, 9.0</h4>
          <ol>
            <li>Click "Tools" at the top of your browser and select "Internet Options", then click the "Privacy" tab.</li>
            <li>Check that the level of your privacy is set to Medium or lower, which will allow the use of cookies in your browser.</li>
            <li>If set above medium level it will prevent the use of cookies.</li>
          </ol>
          <h4 class="card-title">Mozilla Firefox</h4>
          <ol>
            <li>Click "Tools" at the top of your browser and select "Options".</li>
            <li>Then select the "Privacy" icon.</li>
            <li>Click the "Cookies" and select "Allow pages to create a cookie."</li>
          </ol>
          <h4 class="card-title">Safari</h4>
          <ol>
            <li>Click the gear icon at the top of your browser and select "Settings".</li>
            <li>Click the "Privacy" tab, then select the option "Disable the use of cookies by third parties and advertising cookies."</li>
            <li>Click "Save".</li>
          </ol>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card mt-3">
        <h3 class="card-header">How to manage cookies on your Mac</h3>
        <div class="card-body">
          <p class="card-text">To enable cookies on our website, follow the steps below.</p>
          <h4 class="card-title">Microsoft Internet Explorer 5.0 on OSX</h4>
          <ol>
            <li>Click on "Explorer" at the top of your browser and select "Settings".</li>
            <li>Scroll down to the "Cookies" section in the "Received Files".</li>
            <li>Select "Do not ask."</li>
          </ol>
          <h4 class="card-title">Safari on OSX</h4>
          <ol>
            <li>Click "Safari" on the top of your browser and select "Settings".</li>
            <li>Click the "Privacy" and then "Enable cookies."</li>
            <li>Select "only the pages you have visited."</li>
          </ol>
          <h4 class="card-title">Mozilla and Netscape on OSX</h4>
          <ol>
            <li>Click "Mozilla" or "Netscape" at the top of your browser and select "Settings".</li>
            <li>Scroll down to the "Cookies" under "Privacy & Security".</li>
            <li>Select "Allow cookies only to the original site."</li>
          </ol>
          <h4 class="card-title">Opera</h4>
          <ol>
            <li>Click "Menu" on the top of your browser and select "Settings".</li>
            <li>Then select "Options" tab and the "Advanced".</li>
            <li>Select "Enable cookies."</li>
          </ol>
        </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Welcome to <%= t 'site.long_title' %></h1>
    <p>This is the home page for the <%= t 'site.short_title' %> application. This application demonstrates usage of Rails 5.1 together with Bootstrap 4 and Devise 4.3.</p>
    <p>Additionally, it explains how to add the <code>gem 'devise-fido-usf'</code> to Devise which allows for authentication using a second factor, i.e. a FIDO U2F security token like the Yubico key.</p>
    <p>After registering a user account, you are able to <strong>register FIDO U2F devices</strong> to your <%= link_to 'account', edit_user_registration_path %>. This enables <strong>two-factor authentication</strong> with such devices for your account. If you are not signed in and trying to visit <%= link_to 'a protected page', protected_pages_path %> you are <strong>required</strong> to authenticate additionally with your <strong>FIDO U2F token</strong> besides your usual email / password credentials.</p>
    <p>Please ensure that you serve this page over an <strong>https</strong> connection, i.e. by using <code>thin start --ssl</code>. Otherweise FIDO U2F authentication will not work.</p>
  </div>
</div>

app/views/protected_pages/show.html.erb
<div class="container">
  <h1 class="display-3">Protected Page</h1>
  <p>This is the protected page.</p>
  <p>You can register FIDO U2F devices at your <%= link_to 'account', edit_user_registration_path %> page.</p>
</div>